---
title: Compound specific isotope analsyis of AMD cod - carbon fingerprinting
author: "OEC"
date: "07/10/2024"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
Load packages

# Load packages
```{r, echo=FALSE}
library(dplyr)
library(ggplot2)
library(data.table)
library(tidyr)
library(stringr)
library(Hmisc)
library(ggpubr)
library(googlesheets4)
library(rjags)
library(patchwork) 

# Load colour palette 
colors <- c("Moraes" = "darkgreen", "Jabuticabeira II" = "#56B4E9", "Piacaguera" = "orange", "Morro do Ouro" = "maroon4")
```



#Create a colour pallette

```{r}
cols <- c("Jabuticabeira II" = "#56B4E9", "Moraes" = "#009E73", "Piaçaguera" = "#E69F00", "Morro do Ouro" = "#F0E442", "terrestrial_herbivore" = "#999933","terrestrial_omnivore" = "#CC79A7", "marine_fauna" = "#0072B2")

order <- c("Jabuticabeira II", "Moraes", "Piaçaguera", "Morro do Ouro", "terrestrial_herbivore","terrestrial_omnivore", "marine_fauna")

order <- c("Jabuticabeira II", "Moraes", "Piaçaguera", "Morro do Ouro")

cols1 <- c("Jabuticabeira II" = "#56B4E9", "Moraes" = "#009E73", "Piaçaguera" = "#E69F00", "Morro do Ouro" = "#F0E442", "Freshwater" = "#999999", "Marine" = "#0072B2", "C3 Fauna" = "#000000", "C3 Humans" = "#D55E00", "C4_humans" = "#CC79A7") 
          
order1 <- c("Jabuticabeira II","Morro do Ouro", "Piaçaguera", "Moraes", "Piaçaguera","Morro do Ouro", "Freshwater", "Marine", "C3 Fauna", "C3 Humans", "C4_humans") 
```





#1 Load data 

```{r}
library (here)
Data  <-  read.csv(here('data','SambaquisAA.csv'))
data <- data %>% rowwise() %>% mutate(glugly_15N = (c(glu_d15N - gly_d15N)))
humans <-filter(data, group == "Human")
fauna <-filter(data, group == "Fauna")
```


```{r}
library(ggrepel)
library(here)
Fig6a <-ggplot()+
  labs(y=expression(delta^{15}*N[gly]*"(\u2030)"), x=expression(delta^{15}*N[phe]*"(\u2030)"))+
  scale_x_continuous(position="bottom", limits=c(0,20))+
  scale_y_continuous(position = "left", limits=c(0,20))+
 geom_point(data=fauna, aes(y=gly_d15N, x=phe_d15N, fill=category), colour="black", alpha=0.8, pch=23, size=4)+
  geom_point(data=humans, aes(y=gly_d15N, x=phe_d15N, fill=Site), colour="black",  alpha=0.8, pch=21, size=4)+
  geom_text_repel(data=fauna, aes(y=gly_d15N, x=phe_d15N, label=common_name), size=2.5)+ 
  scale_fill_manual(values=c(cols), breaks=c(order))+
    theme_bw()+
  coord_fixed(ratio = 1)
Fig6a
```

```{r}
Fig6b <-ggplot()+
  labs(y=expression(delta^{15}*N[gly]*"(\u2030)"), x=expression(delta^{15}*N[collagen]*"(\u2030)"))+
  scale_x_continuous(position="bottom", limits=c(0,20))+
  scale_y_continuous(position = "left", limits=c(0,20))+
 geom_point(data=fauna, aes(y=gly_d15N, x=d15N, fill=category), colour="black", alpha=0.8, pch=23, size=4)+
  geom_point(data=humans, aes(y=gly_d15N, x=d15N, fill=Site), colour="black",  alpha=0.8, pch=21, size=4)+
  geom_text_repel(data=fauna, aes(y=gly_d15N, x=d15N, label=common_name), size=2.5)+ 
  scale_fill_manual(values=c(cols), breaks=c(order))+
    theme_bw()+
  coord_fixed(ratio = 1)
Fig6b
```
```{r}
Fig6c <-ggplot()+
  labs(y=expression(delta^{15}*N[gly]*"(\u2030)"), x=expression(delta^{15}*N[glx]*"(\u2030)"))+
  scale_x_continuous(position="bottom", limits=c(0,30))+
  scale_y_continuous(position = "left", limits=c(0,20))+
 geom_point(data=fauna, aes(y=gly_d15N, x=glu_d15N, fill=category), colour="black", alpha=0.8, pch=23, size=4)+
  geom_point(data=humans, aes(y=gly_d15N, x=glu_d15N, fill=Site), colour="black", alpha=0.8,  pch=21, size=4)+
  geom_text_repel(data=fauna, aes(y=gly_d15N, x=glu_d15N, label=common_name), size=2.5)+ 
  scale_fill_manual(values=c(cols), breaks=c(order))+
    theme_bw()+
  coord_fixed(ratio = 1.3)
Fig6c
```


#Compile Figure 6

```{r}
library(ggpubr)
Fig6 <- ggarrange(Fig6b, Fig6c,
                    labels = c("A", "B"),
                    ncol = 2, nrow = 1, common.legend = TRUE, legend="bottom" )
Fig6
ggsave(here('figures','Fig6.svg'), width = 17.8, height = 8.9, dpi = 300, units = "cm", device='svg')
```




#Plot glu-gly offest 


```{r}
cols <- c(human = "#F0E442", "marine_fauna" = "#56B4E9", "terrestrial_fauna" = "#009E73")

cols <- c("human" = "#F0E442", "terrestrial_herbivore" = "#999933","terrestrial_omnivore" = "#CC79A7", "marine_fauna" = "#0072B2")

order <- c("human", "terrestrial_herbivore","terrestrial_omnivore", "marine_fauna")

Box <-ggplot()+
  labs(y=expression(Delta^{15}*N[glx-gly]*"(\u2030)"))+
  scale_y_continuous(position = "left", limits=c(0,20))+
 geom_point(data=data, aes(x=Sample_ID, y=glugly_15N, fill=category),size=3, colour="black", pch=21)+
  scale_fill_manual(values=c(cols))+
  theme_bw()+
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
Box
```

